INSERT INTO employeeDB (id,first_name,last_name,job_code) VALUES (5,'nikhil','xyz',555);
INSERT INTO employeeDB (id,first_name,last_name,age,job_code) VALUES (6, 'ABCD', 'XYVZ', 32, 333);
SELECT * FROM employeeDB WHERE first_name='nikhil' OR last_name='sharma';
SELECT * FROM employeeDB WHERE id>1 AND age>=34;
SELECT * FROM employeeDB WHERE id BETWEEN 2 and 5;
SELECT * FROM employeeDB WHERE first_name LIKE 'nikhil';
SELECT * FROM EmployeeDB WHERE age IS NULL;
SELECT * FROM employeeDB WHERE age IN (34,12,41);
SELECT * FROM employeeDB WHERE first_name LIKE '%i%';
SELECT DISTINCT first_name FROM employeeDB; 
SELECT AVG(age) FROM employeeDB;
SELECT MAX(age) FROM employeeDB;
SELECT MIN(age) FROM employeeDB;
SELECT COUNT(*) FROM employeeDB; 
SELECT SUM(age) FROM employeeDB;
SELECT MIN(age),MAX(age),job_code FROM employeeDB GROUP BY job_code;
SELECT MIN(age),MAX(age),job_code FROM employeeDB GROUP BY job_code HAVING COUNT(job_code)>=2;
SELECT * FROM employeeDB ORDER BY age DESC;
SELECT * FROM employeeDB ORDER BY age;
SELECT * FROM employeeDB;
